### ISSUE TITLE
Travis CI integration example. Some irrational fatals.

### ISSUE THREAD

**Issue by jaroslw** [phpbb/phpbb-translation-validator#25]
I'm not sure if it's the right place to ask this question but it might be useful for other translation groups.

I decided to integrate this validator with Polish translation after next deny at phpbb.com. The README file tells a little about running it with Travis CI and required runtime parameters. Finally I've got it working with https://github.com/phpbb-pl/phpbb-translation but is it right implemented?

Validator outputs some irrational fatals such as:
```
Fatal in language/pl/LICENSE:
Missing required file

Fatal in LICENSE:
Found additional file
```
or
````
Fatal in common.php:NUM_ATTACHMENTS:
Plural array has additional case: 3
```
which is a part of plural rules (https://wiki.phpbb.com/Plural_Rules).

Full output: https://travis-ci.org/phpbb-pl/phpbb-translation/jobs/46546623

Are some of these errors currently ignored during Language Packs approval process? Are additional HTML tags allowed to improve readability?

**Comment by nickvergessen** [comment]
Fatals have to be removed, Errors, Warnings and Notices might be ignored.

But your travis implementation is almost right.
Once a version is branched off, https://github.com/phpbb-pl/phpbb-translation/blob/ascraeus/.travis.yml#L12 the develop-ascraeus branch might be different from what your translation needs to be like.
I'd advice to use the release-3.1.* tags then.

**Comment by jaroslw** [comment]
What about two mentioned fatals? LICENSE file is present in right location. Third plural form is required in Polish language (which is also mentioned on phpBB wiki) but here it's marked as fatal.

**Comment by nickvergessen** [comment]
For the license use `language-dir` instead of `package-dir` in your call.

That might also fix the plural thing

**Comment by jaroslw** [comment]
Thanks. Indeed that helped for that fatal errors.
