### ISSUE TITLE
Additional html should not always be warning

### ISSUE THREAD

**Issue by Senky** [phpbb/phpbb-translation-validator#27]
According to [Submission policy](https://github.com/phpbb/phpbb-translation-policies/blob/develop-ascraeus/guidelines.md), `TRANSLATION_INFO` can contain up to 3 additional links. Validator, however, generates warning when I add a link to this entry. Either `notice` level should be used, or even better, no output should be generated until 3 links limit is exceeded.

The same should apply for `help_bbcode.php`: `Linking to another site`, where translator might want to use different words to explain email tag (i.e. in Slovak: `<a href="mailto:meno.priezvisko@adresa.sk">`.

Next: `install.php`: `CONVERT_COMPLETE_EXPLAIN` and `INSTALL_CONGRATS_EXPLAIN`, where translator might want to add a link to official local support site.

**Comment by nickvergessen** [comment]
Yes HTML should be a warning, vecause it requires custom validation. It does not block validation, that's why it is not an error.
