### ISSUE TITLE
Img with /> and > lead to fatal error (HTML5 support)

### ISSUE THREAD

**Issue by Crizz0** [phpbb/phpbb-translation-validator#45]
https://github.com/phpbb/phpbb-translation-validator/pull/43#issuecomment-354446120

**Comment by battye** [comment]
What do you want the expected behavior for this to be? To allow `img` html tags to pass without errors?

So I take a random key:

	'CAPTCHA_RECAPTCHA'				=> 'reCaptcha',

---

Turn it into:

	'CAPTCHA_RECAPTCHA'				=> 'reCaptcha <img src="test.png" />',
	'CAPTCHA_RECAPTCHA'				=> 'reCaptcha <img src="test.png">',

Which results in:

```
Fatal in language/de/captcha_recaptcha.php:CAPTCHA_RECAPTCHA:
String is using additional html: <img src="test.png" />

Fatal in language/de/captcha_recaptcha.php:CAPTCHA_RECAPTCHA:
String is using additional html: <img src="test.png">
```

**Comment by Crizz0** [comment]
The problem iirc was, that e.g. French translators changed everything to HTML5, where phpBB en was still HTML5 and xhtml1.0. so the validator complained, that there was additional html used. I think I did a bloody dirty workaround. But need to look it up.

**Comment by Crizz0** [comment]
@MilesCellar Do you still have this problem? 

Could you the describe it in your words?

**Comment by milescellar** [comment]
No, I no longer have the issue. If it resurfaces, I will reopen a issue for it.

Thank you! 👍
