### ISSUE TITLE
Improve support for RTL languages

### ISSUE THREAD

**Issue by Crizz0** [phpbb/phpbb-translation-validator#48]
Some RTL (right to left) languages, like Arabic etc. need not only a translated "online"-image, but they need extra CSS to display it correctly. Or increase in some point the font size or similar fixes.

But I am not sure, if this should be fixed in phpBB-core for RTL support or if we should be more tolerant in allowing additional rules for RTL languages.

**Comment by battye** [comment]
How do we know if a language is RTL when running it through T.V.? And what would being more tolerant involve? Would we suppress errors, etc?

**Comment by Crizz0** [comment]
We have this: https://github.com/phpbb/phpbb/blob/master/phpBB/language/en/common.php#L45 

Yes, maybe we transform a FATAL error into a Warning or Error, there. But only in certain limits.

**Comment by battye** [comment]
Okay, so we can check if DIRECTION === 'rtr'.

If at some point you can make a list of the cases where you would like fatal turned into warning or error, I don't mind applying the code changes :)
