### ISSUE TITLE
Check ReCATPCHA setting against allowed values

### ISSUE THREAD

**Issue by Crizz0** [phpbb/phpbb-translation-validator#49]
That is quite simple. Here we need something, that checks this line:
'RECAPTCHA_LANG' => 'en-GB', // Find the language/country code on https://developers.google.com/recaptcha/docs/language - If no code exists for your language you can use "en" or leave the string empty
in `\language\en\captcha_recaptcha.php`

if the entry has a valid value from here: https://developers.google.com/recaptcha/docs/language

Regards

**Comment by battye** [comment]
@Crizz0 If you are able to provide a description of what you want for each of these changes (even for all of the other Issues in this repo too), and details of how such a change would be tested - I don't mind having a look at some of these tasks and making some changes when I have time. It would be cool if we could close out of all of the issues in here.

Currently, I don't really understand what "Check ReCATPCHA setting against allowed values", "Improve support for RTL languages", etc means though 😝

**Comment by Crizz0** [comment]
Hi,

that is quite simple. For #49 we need something, that checks this line:
`'RECAPTCHA_LANG'				=> 'en-GB', // Find the language/country code on https://developers.google.com/recaptcha/docs/language - If no code exists for your language you can use "en" or leave the string empty`

if the entry has a valid value from here: https://developers.google.com/recaptcha/docs/language 

Regards
