### ISSUE TITLE
--verbose not working

### ISSUE THREAD

**Issue by scootergrisen** [phpbb/phpbb-translation-validator#61]
Cant seem to use --verbose as described in help text:

> --verbose (-v|vv|vvv)   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

With "--verbose=1" i get:

> [RuntimeException]
>   The "--verbose" option does not accept a value.
> 

Using phpbb-translation-validator-1.4.1.zip

**Comment by DavidIQ** [comment]
We are on version 1.5.1. Did you make a typo?

**Comment by DavidIQ** [comment]
Should be using 1.5.1 available in the releases area of this repo.

**Comment by scootergrisen** [comment]
Same with 1.5.1.

With the text:

    --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

I would think i could do:

    --verbose=1
    --verbose=2
    --verbose=3

But maybe 1, 2, 3 is the number of v's?

    -v
    -vv
    -vvv

Using just "--verbose" seems to give the same output as without it.

**Comment by paul999** [comment]
Verbose doesn't expect a value, you just use --verbose. However, I don't think anything extra is outputted in verbose mode.

**Comment by Crizz0** [comment]
`--display-notices` will give you everything the validator can output.
