### ISSUE TITLE
-V not showing version number

### ISSUE THREAD

**Issue by scootergrisen** [phpbb/phpbb-translation-validator#62]
-V only shows:
Console Tool

There is no version number.

Using phpbb-translation-validator-1.4.1.zip

**Comment by DavidIQ** [comment]
Same here we are on version 1.5.1. Did you make a typo?

**Comment by scootergrisen** [comment]
No its the one on https://www.phpbb.com/community/viewtopic.php?f=79&t=2205631#p13425776

**Comment by DavidIQ** [comment]
Then you're on the wrong version.

**Comment by scootergrisen** [comment]
Same in 1.5.1.

**Comment by paul999** [comment]
The parameter is something we inherit from symfony it looks like, but we never set the version, and thats why it shows empty.

**Comment by DavidIQ** [comment]
I'll just leave this open for now then in case @Crizzo wants to implement. Otherwise he can close as there is no indication we were going to implement this command anyways.

**Comment by battye** [comment]
Showing the version is easy to add, I've put a PR at https://github.com/phpbb/phpbb-translation-validator/pull/63
